# sqlalchemy_pymysql로 수집한 데이터 DB에 저장하기_환율정보

In [88]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\hmabc\miniforge3\envs\fintech\lib\site-packages (2.0.46)
Requirement already satisfied: pymysql in c:\users\hmabc\miniforge3\envs\fintech\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\hmabc\miniforge3\envs\fintech\lib\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hmabc\miniforge3\envs\fintech\lib\site-packages (from sqlalchemy) (4.15.0)

In [2]:
!pip install cryptography

Requirement already satisfied: cryptography in c:\users\hmabc\miniforge3\envs\fintech\lib\site-packages (46.0.4)
Requirement already satisfied: cffi>=2.0.0 in c:\users\hmabc\miniforge3\envs\fintech\lib\site-packages (from cryptography) (2.0.0)
Requirement already satisfied: typing-extensions>=4.13.2 in c:\users\hmabc\miniforge3\envs\fintech\lib\site-packages (from cryptography) (4.15.0)
Requirement already satisfied: pycparser in c:\users\hmabc\miniforge3\envs\fintech\lib\site-packages (from cffi>=2.0.0->cryptography) (2.22)

In [89]:
import os
import pandas as pd
from sqlalchemy import create_engine, text
import pymysql
pymysql.install_as_MySQLdb()
from dotenv import load_dotenv
load_dotenv()

True

In [90]:
dbid= os.getenv("dbid")
dbpw = os.getenv("dbpw")
host = os.getenv("host")
port = os.getenv("port")

In [92]:
data = pd.read_csv("./상장기업정보.csv")
data

,주식종목,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,유가증권,명인제약,317450,의약품 제조업,"신경정신계열, 구강계열 완제의약품",2025-10-01,12월,이행명,http://www.myunginph.co.kr,경기도
1,코스닥,KB제33호스팩,0072Z0,금융 지원 서비스업,기업인수합병,2025-09-30,12월,박성원,홈페이지 없음,서울특별시
2,코스닥,삼성스팩11호,0071M0,금융 지원 서비스업,기업인수합병,2025-09-30,12월,문소연,홈페이지 없음,서울특별시
3,코스닥,에스투더블유,488280,소프트웨어 개발 및 공급업,"공공/정부기관용 사이버안보 빅데이터 플랫폼, 기업 및 기관용 사이버위협 인텔리전스 ...",2025-09-19,12월,서상덕,http://s2w.inc/,경기도
4,코스닥,오아,342870,가전제품 및 정보통신장비 소매업,계절/생활/주방/건강가전 및 헬스/건강식품,2025-09-09,12월,김상무,http://www.oa-world.com,서울특별시
...,...,...,...,...,...,...,...,...,...,...
2758,유가증권,유한양행,000100,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이..,http://www.yuhan.co.kr,서울특별시
2759,유가증권,CJ대한통운,000120,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,신영수..,http://www.cjlogistics.com,서울특별시
2760,유가증권,경방,000050,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준,..",http://www.kyungbang.co.kr,서울특별시
2761,유가증권,유수홀딩스,000700,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2762,유가증권,한진중공업홀딩스,003480,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,http://www.hhic-holdings.com,경기도

In [93]:
engine = create_engine(f"mysql+pymysql://{dbid}:{dbpw}@{host}:{port}")
conn = engine.connect()

In [94]:
result = conn.execute(text("show databases"))
for row in result:
    print(row)

('fc_account',)
('information_schema',)
('learn_system',)
('mysql',)
('naver_db',)
('performance_schema',)
('sakila',)
('stock_info',)
('sys',)
('univ_lms',)
('world',)

In [95]:
conn.execute(text("use sakila"))

In [96]:
result = conn.execute(text("show tables"))
for row in result:
    print(row)

('actor',)
('actor_info',)
('address',)
('category',)
('city',)
('country',)
('customer',)
('customer_list',)
('film',)
('film_actor',)
('film_category',)
('film_list',)
('film_text',)
('inventory',)
('language',)
('nicer_but_slower_film_list',)
('payment',)
('rental',)
('sales_by_film_category',)
('sales_by_store',)
('staff',)
('staff_list',)
('store',)

In [97]:
result = conn.execute(text("select * from film limit 10;"))
for row in result:
    print(row)

(1, 'ACADEMY DINOSAUR', 'A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies', 2006, 1, None, 6, Decimal('0.99'), 86, Decimal('20.99'), 'PG', 'Deleted Scenes,Behind the Scenes', datetime.datetime(2006, 2, 15, 5, 3, 42))
(2, 'ACE GOLDFINGER', 'A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China', 2006, 1, None, 3, Decimal('4.99'), 48, Decimal('12.99'), 'G', 'Trailers,Deleted Scenes', datetime.datetime(2006, 2, 15, 5, 3, 42))
(3, 'ADAPTATION HOLES', 'A Astounding Reflection of a Lumberjack And a Car who must Sink a Lumberjack in A Baloon Factory', 2006, 1, None, 7, Decimal('2.99'), 50, Decimal('18.99'), 'NC-17', 'Trailers,Deleted Scenes', datetime.datetime(2006, 2, 15, 5, 3, 42))
(4, 'AFFAIR PREJUDICE', 'A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank', 2006, 1, None, 5, Decimal('2.99'), 117, Decimal('26.99'), 'G', 'Commentaries,Behind the Scenes', datetime.datetime(2006, 2, 15, 5, 3, 42))
(5, 'AFRICAN EGG', 'A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico', 2006, 1, None, 6, Decimal('2.99'), 130, Decimal('22.99'), 'G', 'Deleted Scenes', datetime.datetime(2006, 2, 15, 5, 3, 42))
(6, 'AGENT TRUMAN', 'A Intrepid Panorama of a Robot And a Boy who must Escape a Sumo Wrestler in Ancient China', 2006, 1, None, 3, Decimal('2.99'), 169, Decimal('17.99'), 'PG', 'Deleted Scenes', datetime.datetime(2006, 2, 15, 5, 3, 42))
(7, 'AIRPLANE SIERRA', 'A Touching Saga of a Hunter And a Butler who must Discover a Butler in A Jet Boat', 2006, 1, None, 6, Decimal('4.99'), 62, Decimal('28.99'), 'PG-13', 'Trailers,Deleted Scenes', datetime.datetime(2006, 2, 15, 5, 3, 42))
(8, 'AIRPORT POLLOCK', 'A Epic Tale of a Moose And a Girl who must Confront a Monkey in Ancient India', 2006, 1, None, 6, Decimal('4.99'), 54, Decimal('15.99'), 'R', 'Trailers', datetime.datetime(2006, 2, 15, 5, 3, 42))
(9, 'ALABAMA DEVIL', 'A Thoughtful Panorama of a Database Administrator And a Mad Scientist who must Outgun a Mad Scientist in A Jet Boat', 2006, 1, None, 3, Decimal('2.99'), 114, Decimal('21.99'), 'PG-13', 'Trailers,Deleted Scenes', datetime.datetime(2006, 2, 15, 5, 3, 42))
(10, 'ALADDIN CALENDAR', 'A Action-Packed Tale of a Man And a Lumberjack who must Reach a Feminist in Ancient China', 2006, 1, None, 6, Decimal('4.99'), 63, Decimal('24.99'), 'NC-17', 'Trailers,Deleted Scenes', datetime.datetime(2006, 2, 15, 5, 3, 42))

In [98]:
conn.close()

# DB 선택해서 접속하기

In [99]:
engine = create_engine(f"mysql+pymysql://{dbid}:{dbpw}@{host}:{port}/stock_info")
conn = engine.connect()

# pandas dataframe DB에 저장하기
* to_sql("테이블명", con=conn, if_exists="append")

In [100]:
data.to_sql("stock_company_info_2026", con=conn, index=False, if_exists="replace")

2763

# DB에서 테이블을 pandas dataframe으로 불러오기

In [101]:
data2=pd.read_sql("stock_company_info_2026", con=conn)
data2

,주식종목,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,유가증권,명인제약,317450,의약품 제조업,"신경정신계열, 구강계열 완제의약품",2025-10-01,12월,이행명,http://www.myunginph.co.kr,경기도
1,코스닥,KB제33호스팩,0072Z0,금융 지원 서비스업,기업인수합병,2025-09-30,12월,박성원,홈페이지 없음,서울특별시
2,코스닥,삼성스팩11호,0071M0,금융 지원 서비스업,기업인수합병,2025-09-30,12월,문소연,홈페이지 없음,서울특별시
3,코스닥,에스투더블유,488280,소프트웨어 개발 및 공급업,"공공/정부기관용 사이버안보 빅데이터 플랫폼, 기업 및 기관용 사이버위협 인텔리전스 ...",2025-09-19,12월,서상덕,http://s2w.inc/,경기도
4,코스닥,오아,342870,가전제품 및 정보통신장비 소매업,계절/생활/주방/건강가전 및 헬스/건강식품,2025-09-09,12월,김상무,http://www.oa-world.com,서울특별시
...,...,...,...,...,...,...,...,...,...,...
2758,유가증권,유한양행,000100,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이..,http://www.yuhan.co.kr,서울특별시
2759,유가증권,CJ대한통운,000120,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,신영수..,http://www.cjlogistics.com,서울특별시
2760,유가증권,경방,000050,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준,..",http://www.kyungbang.co.kr,서울특별시
2761,유가증권,유수홀딩스,000700,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2762,유가증권,한진중공업홀딩스,003480,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,http://www.hhic-holdings.com,경기도

# 네이버 증권에서 주가 정보 수집하기

In [102]:
import os
import time
import requests
import pandas as pd
from bs4 import BeautifulSoup as bs
from myfunc import text_clean

In [145]:
# url = "https://finance.naver.com/item/main.naver?code=005930"
# r= requests.get(url)
# soup = bs(r.content, "lxml")
# soup

In [104]:
soup.select('#middle dl.blind dd')[:-3]

[<dd>2026년 01월
         28일 14시
         06분 기준 장중</dd>,
 <dd>종목명 삼성전자</dd>,
 <dd>종목코드 005930 코스피</dd>,
 <dd>현재가 162,200 전일대비 상승 2,700
             플러스
             1.69 퍼센트
         </dd>,
 <dd>전일가 159,500</dd>,
 <dd>시가 162,600</dd>,
 <dd>고가 163,200</dd>,
 <dd>상한가 207,000</dd>,
 <dd>저가 160,200</dd>,
 <dd>하한가 111,700</dd>,
 <dd>거래량 22,096,554</dd>,
 <dd>거래대금 3,576,149백만</dd>,
 <dd>오늘의시세 162,200 포인트</dd>,
 <dd>2,700 포인트 상승</dd>,
 <dd>1.69% 플러스</dd>]

In [105]:
result = {}
for idx, dd in enumerate(soup.select('#middle dl.blind dd')[:-3]):
    if idx ==0:
        result['날짜'] = "".join(dd.get_text().split()[:3]).replace("년","-").replace("월","-").replace("일","")
    elif idx == 2:
        temp = dd.get_text().split()
        result['거래소'] = temp[2]
        result[temp[0]] = temp[1]
    elif idx ==3:
        print(dd.get_text().split())
        temp = dd.get_text().split()
        result[temp[0]] = int(temp[1].replace(",", ""))
        if temp[3] =='상승':
            result[temp[2]] = temp[4]
        else:
            result[temp[2]] = -int(temp[4])
        if temp[5] == "플러스": 
            result["증가율"] = temp[6] + "%"
        else: result['증가율'] = "-" + temp[6] + "%"
    else:
        if idx == 1 or idx == 11:
            temp = dd.get_text().split()
            result[temp[0]] = temp[1]
        else:
            temp = dd.get_text().split()
            result[temp[0]] = temp[1].replace(" ","")
            
result

['현재가', '162,200', '전일대비', '상승', '2,700', '플러스', '1.69', '퍼센트']

{'날짜': '2026-01-28',
 '종목명': '삼성전자',
 '거래소': '코스피',
 '종목코드': '005930',
 '현재가': 162200,
 '전일대비': '2,700',
 '증가율': '1.69%',
 '전일가': '159,500',
 '시가': '162,600',
 '고가': '163,200',
 '상한가': '207,000',
 '저가': '160,200',
 '하한가': '111,700',
 '거래량': '22,096,554',
 '거래대금': '3,576,149백만',
 '오늘의시세': '162,200',
 '2,700': '포인트',
 '1.69%': '플러스'}

# 전체 상장 회사 주가정보 수집하기

In [106]:
data2 = pd.read_sql("stock_company_info_2026", con=conn)
data2

,주식종목,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,유가증권,명인제약,317450,의약품 제조업,"신경정신계열, 구강계열 완제의약품",2025-10-01,12월,이행명,http://www.myunginph.co.kr,경기도
1,코스닥,KB제33호스팩,0072Z0,금융 지원 서비스업,기업인수합병,2025-09-30,12월,박성원,홈페이지 없음,서울특별시
2,코스닥,삼성스팩11호,0071M0,금융 지원 서비스업,기업인수합병,2025-09-30,12월,문소연,홈페이지 없음,서울특별시
3,코스닥,에스투더블유,488280,소프트웨어 개발 및 공급업,"공공/정부기관용 사이버안보 빅데이터 플랫폼, 기업 및 기관용 사이버위협 인텔리전스 ...",2025-09-19,12월,서상덕,http://s2w.inc/,경기도
4,코스닥,오아,342870,가전제품 및 정보통신장비 소매업,계절/생활/주방/건강가전 및 헬스/건강식품,2025-09-09,12월,김상무,http://www.oa-world.com,서울특별시
...,...,...,...,...,...,...,...,...,...,...
2758,유가증권,유한양행,000100,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이..,http://www.yuhan.co.kr,서울특별시
2759,유가증권,CJ대한통운,000120,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,신영수..,http://www.cjlogistics.com,서울특별시
2760,유가증권,경방,000050,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준,..",http://www.kyungbang.co.kr,서울특별시
2761,유가증권,유수홀딩스,000700,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2762,유가증권,한진중공업홀딩스,003480,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,http://www.hhic-holdings.com,경기도

In [107]:
codes= data2['종목코드']
codes[:2]

0    317450
1    0072Z0
Name: 종목코드, dtype: object

In [114]:
all_stock_info = []
for code in codes[:3]:

    url = f"https://finance.naver.com/item/main.naver?code={code}"
    r = requests.get(url)
    soup = bs(r.content, "lxml")

    result = {} # 1개 회사의 주가
    for idx, dd in enumerate(soup.select("#middle dl.blind dd")[:-3]):
        if idx == 0:
            result['날짜'] = "".join(dd.get_text().split()[:3]).replace("년", "-").replace("월", "-").replace("일", "")
        elif idx == 2:
            temp = dd.get_text().split()
            result['거래소'] = temp[2]
            result[temp[0]] = temp[1]
        elif idx == 3:
            temp = dd.get_text().split()
            result[temp[0]] = temp[1]
            if temp[3] == "상승":
                result[temp[2]] = int(temp[4].replace(",", ""))
            else:
                result[temp[2]] = -int(temp[4].replace(",", ""))
            if temp[5] == "플러스":
                result["증가율"] = temp[6]+"%"
            else:
                result["증가율"] = "-"+temp[6]+"%"
        else:
            if idx == 1 or  idx == 11:
                temp = dd.get_text().split()
                result[temp[0]] = temp[1]
            else:
                temp = dd.get_text().split()
                result[temp[0]] = temp[1]
    all_stock_info.append(result)
    
    time.sleep(3)
             
df = pd.DataFrame(all_stock_info)
df

,날짜,종목명,거래소,종목코드,현재가,전일대비,증가율,전일가,시가,고가,상한가,저가,하한가,거래량,거래대금,오늘의시세,800,1.22%
0,2026-01-28,명인제약,코스피,317450,"65,000",-800,-1.22%,"65,800","65,200","66,100","85,500","64,900","46,100","52,275","3,418백만","65,000",포인트,마이너스
1,2026-01-28,KB제33호스팩,코스닥,0072Z0,"1,992",0,-퍼센트%,"1,992","1,994","1,996","2,585","1,988","1,395","43,412",86백만,NaN,NaN,NaN
2,2026-01-28,삼성스팩11호,코스닥,0071M0,"2,015",0,-퍼센트%,"2,015","2,015","2,020","2,615","2,015","1,415","48,351",98백만,NaN,NaN,NaN

In [116]:
conn.close()

### 데이터베이스에 접속하는 함수 만들기

In [134]:
def _mysql_url(dbname=None):
    """
    dbname이 있으면 db이름을 포함한 접속주소 출력
    """
    if dbname:
        return f"mysql+pymysql://{dbid}:{dbpw}@{host}:{port}/{dbname}"
    return f"mysql+pymysql://{dbid}:{dbpw}@{host}:{port}"

In [135]:
_mysql_url("stock_info")

'mysql+pymysql://root:1234@127.0.0.1:3306/stock_info'

In [138]:
def db_connect(dbname):
    engine_root = create_engine(_mysql_url())
    conn_root = engine_root.connect()
    conn_root.exectue(text(f"create database if not exists {dbname}"))
    print(f"{dbname} 데이터베이스 확인/생성 완료")
    conn_root.close()
    
    engine = create_engine(_mysql_url(dbname))
    conn=engine.connect()
    return conn

In [140]:
conn = db_connect("stock_info2")

AttributeError: 'Connection' object has no attribute 'exectue'

In [142]:
conn.execute(text("create table test (idx int not null, name varchar(100) not null)"))

ResourceClosedError: This Connection is closed

In [147]:
def to_db(dbname, table_name, df):
    conn = db_connect(dbname)
    df.to_sql(table_name, con=conn, index=False, if_exists="append")
    conn.close()
    print(f"{dbname}.{table_name} 데이터 저장 완료(append)")

In [148]:
from dbio import from_db